version: '3.2'

services:
    gooutsafe:
        depends_on:
            - redis
        restart: always
        build: .
        ports:
            - "5000:5000"
        expose:
            - "5000"
        volumes:
              - ./monolith/db:/code/monolith/db
    celery:
        depends_on:
            - redis
            - gooutsafe
        build: .
        restart: always
        command: celery -A monolith.worker:celery worker --loglevel=info -B -s /tmp/schedule
        volumes:
            - ./monolith/db:/code/monolith/db
        links:
            - redis
    redis:
        image: "redis:alpine"
        container_name: rd01
        expose:
            - "6379"
